### ISSUE TITLE
请教若干问题啊

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-server#1]
Dear zsx，

1、如果我有多个活动需要使用不同的房间来玩弹幕的话是不是在config.js里面配置多个房间就行了？
2、如果你的svn内的服务端代码升级了，那么我这边已经在服务器上安装的老版服务端应该怎么同步升级呢？
3、安装程序会自动安装db到mysql的吧？如果没有memcache应该怎么设置config.js呢？
4、我想在服务器上安装多个server是ok的吧？只需要把db分别配置创建一下就行了，相互独立开？

谢谢。

**Comment by zsxsoft** [comment]
1. 是
2. 你可以本地git更新然后传到服务器上，或者服务器上

```
git stash
git pull 
git stash pop
```

这个是服务器运维的问题。
3. 没有memcached的话直接config.js里把cache的type设为none，见文档

**Comment by phperwuhan** [comment]
对于第2个问题，是不是意味着只需要把你的新版server代码直接覆盖到我的服务器上的server代码就行了，对吧？不需要别的什么命令操作了吧？

**Comment by zsxsoft** [comment]
是

**Comment by phperwuhan** [comment]
4、我想在服务器上安装多个server是ok的吧？只需要把db分别配置创建一下就行了，相互独立开？

**Comment by zsxsoft** [comment]
端口不冲突就行，DB事实上可以装在同个数据库里，把room的table改掉就行

**Comment by phperwuhan** [comment]
5、如果我安装了server并且配置了config，然后后来又想分阶段的增加若干房间，是不是直接修改config增加房间配置就行了？config里面增加的新房间的数据表是会被自动创建的，对吗？

**Comment by zsxsoft** [comment]
是，不过得重启这个服务端程序才行

**Comment by phperwuhan** [comment]
太赞了，呵呵

**Comment by phperwuhan** [comment]
6、我用putty登录并执行nmp start以后，过一段时间服务端就失效了？putty也自己超时不能用了。
有没有什么办法执行nmp start以后能让他一直执行下去的？然后我又可以关闭putty

**Comment by phperwuhan** [comment]
7、现在服务端支持的接口参数有哪些啊？
是不是text,hash,room,color,type,password,textStyle这些啊？
其中hash是写死的吗？还是需要动态生成和传递？

谢谢

**Comment by zsxsoft** [comment]
1. 你这样运行的程序是随Session销毁而被关闭的。要使其后台运行，请以daemon方式启动程序。详情请自行百度。推荐一个Nodejs应用管理程序https://github.com/Unitech/pm2
2. hash由服务器的前端生成，是识别一个人是否本人的标识。如果开启了新浪微博验证，hash将被替换为新浪微博ID。主要就是封号用的。
