### ISSUE TITLE
Bugs with 'strict mode'

### ISSUE THREAD

**Issue by hqy2000** [zsxsoft/danmu-server#13]
When compiling with the latest commit, there is always an error with the 'strict mode'. I try again with the official steps on the readme.md, it still occurs. This will disappear if I add 'use strict' on the top of every file. (nodejs:4.2.6 npm3.5.2)

LOG:
/var/www/chat.nfls.io/danmu-server/src/interfaces/Base.js:4
class Base {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by zsxsoft** [comment]
Testing, please wait

**Comment by hqy2000** [comment]
It will work properly if I use NODEJS V6.9.1 on my server, but still causes bugs under V4.2.6

**Comment by zsxsoft** [comment]
@nfls I see, so I'm checking if my readme have some issues. I hate npm2.

**Comment by zsxsoft** [comment]
That's my fault. In development version, I updated the structure, but forgot to update `package.json`. I'll modify it as soon as possible.

**Comment by hqy2000** [comment]
thx.
By the way, may I ask how to login to the manage page? It seems if I enter /manage, there is always nothing on it. (Chrome)
![image](https://cloud.githubusercontent.com/assets/12138874/19625254/d0d624f4-9945-11e6-8a3f-9f956451532f.png)

**Comment by zsxsoft** [comment]
Click 管理信息

**Comment by hqy2000** [comment]
OK. Thanks a lot.

**Comment by zsxsoft** [comment]
话说回来了，为什么要用英语。。

**Comment by hqy2000** [comment]
Github上用英语用成习惯了😂😂😂

**Comment by hqy2000** [comment]
@zsxsoft 对了，是否能提供实时获取弹幕的接口（不需要密码那种，打算转换成json做在视频直播画面上用）

**Comment by zsxsoft** [comment]
这个……不懂你的意思？你可以看一下客户端的代码吧，数据传递用的WebSocket，格式就是JSON

**Comment by KiritoMiao** [comment]
直接通过接口可以推送
域名:端口/post
发送表单
text=弹幕内容

**Comment by hqy2000** [comment]
@KiritoMiao 
已经开发者工具研究出来了
不过还是谢谢了 
🌚🌚🌚
