### ISSUE TITLE
如何开启全局审核拓展

### ISSUE THREAD

**Issue by ghost** [zsxsoft/danmu-server#14]
config.js 目前这样写 ：
	"ext": {
		"audit": {
		}
	}
start启动之后报错

/root/danmu/config.js:78
                "audit": {
                ^^^^^^^
SyntaxError: Unexpected string

请教下如何正确的开启全局审核拓展。谢谢~

**Comment by zsxsoft** [comment]
把你完整config.js贴出来，去掉rooms的部分

**Comment by zsxsoft** [comment]
我怀疑你"audit"前面有别的项，然后少了逗号

**Comment by ghost** [comment]
嗯嗯，之前的问题确实是少了个逗号。现在添加上去貌似有个新的问题~

[2017-2-28 7:2:29.938] 环境：linux(3.16.0-4-amd64) x64 with 1000MB
[2017-2-28 7:2:29.941] 加载扩展组件：autoban
[2017-2-28 7:2:29.960] 加载扩展组件：audit
module.js:471
    throw err;
    ^

Error: Cannot find module '/root/danmu/lib/ext/ext/audit'



config.js的 ext部分：
"ext": {
                "autoban": {
                        "block": 3, // 被拦截超过一定数字自动封号
                },
"audit": { // 审核扩展
}
 }

**Comment by zsxsoft** [comment]
用新版……
