### ISSUE TITLE
全局审核插件无法推送审核内容至后台

### ISSUE THREAD

**Issue by KiritoMiao** [zsxsoft/danmu-server#15]
配置文件：
module.exports = {
	"rooms": {
		"XDF": {
			"hostname": ["127.0.0.1", "dm.*.*"],
			"cdn": false,			
			"display": "xdf",
			"table": "xdf", // 数据表
			"connectpassword": "xxxx", // 客户端连接密码
			"managepassword": "xxxx", // 管理密码
			"advancedpassword": "xxxx", // 高级弹幕密码
			"keyword": {
				"block": /^$/,
				// 强制屏蔽关键词
				"replacement": /^$/,
				// 替换关键词
				"ignore": /^$/
					// 忽略词
			},
			"blockusers": [ // 封禁用户
				"test"
			],
			"maxlength": 100, // 队列最大长度
			"textlength": 1000, // 弹幕最大长度
			"image": {
				"regex": /\[IMG WIDTH=(\d+)\](.+?)\[\/IMG\]/ig, // 图片弹幕
				"lifetime": 300 // 每个图片给每条弹幕增加的时间
			},
			"permissions": { // 普通用户允许的弹幕权限
				"send": true, // 弹幕开关；关闭后无论普通用户还是高级权限都完全禁止弹幕。
				"style": false, // 弹幕样式开关
				"color": false, // 颜色开关
				"textStyle": false, // CSS开关
				"height": false, // 高度开关
				"lifeTime": false, // 显示时间开关
				"sourceCode": false, // 自定义高级JavaScript弹幕开关
			}
		},
	},
	"database": {
		"type": "mysql", // 数据库类型（mysql / mongo / csv / none）
		"server": "127.0.0.1", // 数据库地址（mysql / mongo）
		"username": "root", // 数据库用户名（mysql / mongo）
		"password": "xxxx", // 数据库密码（mysql / mongo）
		"port": "3306", // 数据库端口（mysql / mongo）
		"db": "danmu", // 数据库（mysql / mongo）
		"retry": 10, // 24小时允许断线重连最大次数，超过则自动退出程序。24小时以第一次断线时间计。（mysql）
		"timeout": 1000, // 数据库重连延时及Ping（mysql）
		"savedir": "./", // 指定文件保存位置（csv）
	},
	"websocket": {
		"interval": 10, // 弹幕发送间隔
		"singlesize": 5 // 每次弹幕发送数量
	},
	"http": {
		"port": 3000, // 服务器端口
		"headers": { // HTTP头
		},
		"sessionKey": "2333"
	},
	"cache": {
		"type": "memcached", // 缓存类型，支持memcached和aliyun。后者需要npm install aliyun-sdk
		"host": "127.0.0.1:11211", // 缓存服务器地址，可用socket
		"auth": false, // 是否打开身份验证
		"authUser": "", // 身份验证账号
		"authPassword": "" // 身份验证密码
	},
	"ext": {
		"audit": {
		},
		"livesync": { // 新浪微博扩展
			"XDF": {
				"liveUrl": 'http://live.bilibili.com/132864', // 直播网站地址
			}
		}
	}
};

**Comment by KiritoMiao** [comment]
![default](https://cloud.githubusercontent.com/assets/8502542/26022741/4daa3b04-37df-11e7-9d31-b40dff0b739f.png)

**Comment by KiritoMiao** [comment]
npm@3.10.9 /usr/local/nodejs7/node-v7.1.0-linux-x64/lib/node_modules/npm

**Comment by KiritoMiao** [comment]
发现不兼容原因为memcached/nodejs 7

**Comment by zsxsoft** [comment]
嗯？你说哪个地方不兼容？？？

**Comment by KiritoMiao** [comment]
启用memcached后，可能是链接失败。
建议加下连接失败提示

**Comment by zsxsoft** [comment]
你在后台页面F12->Console看一下？

**Comment by KiritoMiao** [comment]
已经格式化掉了，换了环境好了
