### ISSUE TITLE
弹幕发送的速度控制

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-server#2]
Dear zsx,

我这边设置了服务器端的若干参数，希望控制弹幕发送的速度能够慢一些均匀一些，不要出现一下同时出来很多弹幕（高并发）一下又没有弹幕出来（低并发或无弹幕）的情况，可我设置好了以后貌似效果不怎么明显，以下是我设置几个参数，想听听你的意见：
"maxlength": 100, // 队列最大长度，这个还是采用默认的100个弹幕的队列的设置；

"textlength": 500 // 弹幕最大长度，由于会包含表情地址，所以这里设置得比较大，后面我会尝试用本地表情图片把这里再改小

"interval": 1000, // 弹幕发送间隔，比默认设置大很多，我们希望的效果是一个弹幕出来以后，下一个弹幕隔个5秒左右才出来，不知道这里设置的是否对，好像没有效果

"singlesize": 1 // 每次弹幕发送数量，一次发一个弹幕，跟interval参数配合，但是好像没有效果。。。

谢谢

**Comment by zsxsoft** [comment]
你都隔5秒了interval当然要5000了……

**Comment by phperwuhan** [comment]
哦
队列长度设置为100的话，如果并发量超过了100，多出的弹幕是会被丢掉吗？

**Comment by zsxsoft** [comment]
http://blog.zsxsoft.com/post/14

> 将原始的弹幕记录到数据库，同时加入双向队列。队列大小一定。若过大，则需要从队列头出队列，原因是因为太老的弹幕没有意义。工作线程每隔一定时间自动从队列尾弹出需要的内容发送到客户端，服务端整套流程完成。

**Comment by phperwuhan** [comment]
那个blog里面的弹幕太眩了，赞

**Comment by zsxsoft** [comment]
来两条地址，是我开新浪微博后的
http://weibo.com/3115658185/Cgtldsu0x
