### ISSUE TITLE
怎么关闭弹幕服务？

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-server#4]
如题，除了npm start开始弹幕服务以外，如果想关闭弹幕服务，应该怎么做？

我试着执行npm stop好像报错，说没有这个脚本。。。

**Comment by zsxsoft** [comment]
Ctrl+C或ps后kill。
这些基础的东西请自己搜索。
2015年9月8日 11:37于 phperwuhan notifications@github.com写道：如题，除了npm start开始弹幕服务以外，如果想关闭弹幕服务，应该怎么做？

我试着执行npm stop好像报错，说没有这个脚本。。。

**Comment by phperwuhan** [comment]
好吧，还以为会有专门的stop命令来做这个事情。

**Comment by phperwuhan** [comment]
请关闭这个issue

**Comment by phperwuhan** [comment]
我把npm和node这2个pid都kill掉了。
