### ISSUE TITLE
mysql定时关闭连接？

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-server#6]
Dear zsx,

我这边发现弹幕服务端总是在每天下午5点20多分钟的时候断开了mysql的连接并报错，你知道这是服务端程序自动断开的mysql连接还是mysql服务器出的问题啊？

**Comment by zsxsoft** [comment]
我明天中午回家，一并解答+解决。

**Comment by phperwuhan** [comment]
:+1:

**Comment by phperwuhan** [comment]
我的同事说有可能是mysql的wait_timeout超时以后由mysql自动关掉连接的，有没有可能优化一下服务端代码让他可以判断是否需要自动重新再连mysql？这样的话服务端是不是就可以长时间在线服务了？会更优。

**Comment by zsxsoft** [comment]
我知道了，就是超时事件这里要做重连的问题，论程序的鲁棒性
2015年9月11日 下午2:06于 phperwuhan notifications@github.com写道：我的同事说有可能是mysql的wait_timeout超时以后由mysql自动关掉连接的，有没有可能优化一下服务端代码让他可以判断是否需要自动重新再连mysql？这样的话服务端是不是就可以长时间在线服务了？会更优。
