### ISSUE TITLE
包含一个图片时比包含多个图片滚动快很多

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-server#8]
Dear zsx,

我使用最新版server和client以后通过控制server中的lefttime可以把包含多个图片和不包含图片的弹幕控制成差不错一样滚动速度。

但是我发现，当弹幕中仅仅只有一个图片或者包含多个文字和一个图片时，弹幕的滚动速度比包含多个图片和不包含图片的弹幕快很多，差不多是2比1的关系。

不知这是什么原因？有办法控制得都一样快吗？

我本地把server端的lefttime和client端的lefttime都设置为了2000，然后height=70。

谢谢

**Comment by phperwuhan** [comment]
PS:当仅仅只有一个图片时速度最快。

**Comment by zsxsoft** [comment]
server里有个图片增加时间，你看下

**Comment by zsxsoft** [comment]
server的config里有个配置

**Comment by phperwuhan** [comment]
我知道啊，我都设置成2000了

**Comment by phperwuhan** [comment]
你可以把server端的lefttime和client端的lefttime都设置为2000，观察看看是不是可以重现这个问题哦。

**Comment by zsxsoft** [comment]
嘛，这里我测试过应该没什么问题的。周五看下

**Comment by zsxsoft** [comment]
我这里的测试结果是，带图片的情况下比不带图片慢。

**Comment by phperwuhan** [comment]
我的天，怎么会这样？

你的配置跟我一样的吗？

我这边server端的lefttime和client端的lefttime都设置为了2000，然后client端的height=70，并且我这边调用弹幕接口时的height参数也是70。

另外我本地client是在win7环境下跑的。

有可能是什么原因引起的呢？。。。

**Comment by phperwuhan** [comment]
另外，我这边调用服务端弹幕接口是这样的地址url：
http://ip地址:3006/post

传递的接口数据包括：
text
hash
room
color
type = 'advanced'
password
textStyle（例如：normal bold 6em 微软雅黑）

server端的其他一些配置是这样的：
"interval": 4000,
"singlesize": 1
cache被禁用，autoban被注释掉了

client端的其他一些配置是这样的：
        comment: {
            animationStyle: "scroll",
            fontStyle: "normal bold 5em 微软雅黑",
            fontColor: "rgb(255, 255, 255)",
            lifeTime: 2000,
            height: 70
        },
        image: true

**Comment by zsxsoft** [comment]
服务器配置有更新，你可能少了配置。重新复制一下比较合适

**Comment by phperwuhan** [comment]
我是十一以后把代码全部更新来设置的，应该跟git上的配置文件一样的哦

只是根据自己的需求改了一下配置值。

**Comment by zsxsoft** [comment]
你试试默认配置先跑一遍看看

**Comment by phperwuhan** [comment]
Dear zsx,

试着用默认配置重新安装测试了一下：
1、没有图片时比有图片时快很多；
2、有一个图片时比有多个图片时快一些；
3、有多个图片时速度比较均匀，差别不是很大；

在支持csv格式以前的速度控制好像比现在要正常一点，那个时候的情况是内容越多滚动速度越快。
这块有优化的方案吗？

谢谢

**Comment by zsxsoft** [comment]
有图片的情况下，每张图片增加1000fps（约16秒）的时间，我现在调整为了300fps（约5秒）。见配置。
