### ISSUE TITLE
扩展字段请教

### ISSUE THREAD

**Issue by phperwuhan** [zsxsoft/danmu-server#9]
亲，

请教一下，如果在调用server端接口时每个弹幕额外多发几个扩展字段的信息（除了默认的text/hash/room/color/type/password/textStyle字段以外），在客户端中能直接收到这几个扩展字段的值吗？如果能，server端应该不需要做什么修改吧？

谢谢

**Comment by zsxsoft** [comment]
见最新的第二条和第四条Commit Log。
我觉得有的东西你还是自己研究一下合适，也没几行代码。
On Nov 3, 2015 12:22, phperwuhan notifications@github.com wrote:亲，

请教一下，如果在调用server端接口时每个弹幕额外多发几个扩展字段的信息（除了默认的text/hash/room/color/type/password/textStyle字段以外），在客户端中能直接收到这几个扩展字段的值吗？如果能，server端应该不需要做什么修改吧？

谢谢

**Comment by phperwuhan** [comment]
:+1:
